### ISSUE TITLE
[Suggestion] Better Combat support

### ISSUE THREAD

**Issue by Pirogiran** [sussy-syrup/Smithees-Foundry-Compat#1]
I think support for [Better Combat](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus) will be very cool!
There some combat changes and animations.

**Comment by sussy-syrup** [comment]
This was surprisingly easier than I thought it would be. Will be in the next release which will focus mainly on compat. No new features so should be out soon
